steps:
  - name: 'circleci/node:8-browsers'
    args: ['node', '--version']
  - name: 'circleci/node:8-browsers'
    entrypoint: 'yarn'
    args: ['--version']
  - name: 'circleci/node:8-browsers'
    entrypoint: 'sudo'
    args: ['yarn', 'install']
  - name: 'circleci/node:8-browsers'
    entrypoint: 'sudo'
    args: ['chmod','-R','777', '/workspace']
  - name: 'circleci/node:8-browsers'
    entrypoint: 'yarn'
    args: ['build']
  - name: 'circleci/node:8-browsers'
    entrypoint: 'cp'
    args: ['config/ci.config.json', 'config/project.json']
  - name: 'circleci/node:8-browsers'
    entrypoint: 'sudo'
    args: ['yarn', 'test']
timeout: 1800s
options:
 machineType: 'N1_HIGHCPU_32'