steps:
  - name: 'circleci/node:8-browsers'
    args: ['node', '--version']
  - name: 'circleci/node:8-browsers'
    entrypoint: 'ls'
    args: ['-al']
  - name: 'gcr.io/cloud-builders/gsutil'
    id: 'read node_modules from cache'
    args: ['cp','gs://ossbot-f0cad.appspot.com/nodem.zip' , 'nodem.zip' ]
  - name: 'circleci/node:8-browsers'
    entrypoint: 'sudo'
    args: ['yarn', 'install']
  - name: 'circleci/node:8-browsers'
    entrypoint: 'sudo'
    args: ['chmod','-R','777', '/workspace']
  - name: 'circleci/node:8-browsers'
    entrypoint: 'zip'
    args: ['-r', 'nodem.zip', 'node_modules']
  - name: 'gcr.io/cloud-builders/gsutil'
    id: 'cache node_modules'
    args: ['cp', '-r', 'node_modules', 'gs://ossbot-f0cad.appspot.com/nodem.zip']
  - name: 'circleci/node:8-browsers'
    entrypoint: 'sudo'
    args: ['yarn', 'build']
  - name: 'circleci/node:8-browsers'
    entrypoint: 'cp'
    args: ['config/ci.config.json', 'config/project.json']
  - name: 'circleci/node:8-browsers'
    entrypoint: 'sudo'
    args: ['yarn', 'test']
timeout: 1800s
options:
 machineType: 'N1_HIGHCPU_32'