steps:
  - name: 'node:8'
    args: ['node', '--version']
  - name: 'node:8'
    entrypoint: 'npm'
    args: ['--version']
  - name: 'node:8'
    entrypoint: 'npm'
    args: ['install']
  - name: 'node:8'
    entrypoint: 'npm'
    args: ['test']