# Use the latest 2.1 version of CircleCI pipeline processing engine, see https://circleci.com/docs/2.0/configuration-reference/
version: 2.1

# Use a package of configuration called an orb, see https://circleci.com/docs/2.0/orb-intro/
orbs:
  # Declare a dependency on the welcome-orb
  welcome: circleci/welcome-orb@0.3.1

jobs:
  build:
    docker:
      - image: circleci/node:8-browsers # comes with Java8
    # machine: true
    steps:
      - checkout
      # - run: |
      #     echo 'export NVM_DIR="/opt/circleci/.nvm"' >> $BASH_ENV
      #     echo ' [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"' >> $BASH_ENV
      - run: python -V
      # - run: 
      #     name: Upgrade node and Install yarn
      #     command: |
      #       node -v
      #       nvm install v8.11.3
      #       nvm alias default v8.11.3
      #       node -v
      - run: node -v
      - run: cp config/ci.config.json config/project.json
      - run: yarn install --frozen-lockfile
      - run: yarn build
      - run: yarn test
      - run: echo "finsihed build"

# Orchestrate or schedule a set of jobs, see https://circleci.com/docs/2.0/workflows/
workflows:
  # Name the workflow "Welcome"
  Welcome:
    # Run the welcome/run job in its own container
    jobs:
      - welcome/run
      - build